spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:treble_db}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Password1}
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database: mysql
#    show-sql: true

treble:
  openapi:
    dev-url: http://${DEV_URL_BASE:localhost}:${APP_PORT:8080}
    prod-url: TBC