spring:
  datasource:
    url: jdbc:mysql://localhost:3306/treble_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Password1
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database: mysql
#    show-sql: true

treble:
  openapi:
    dev-url: http://localhost:8080
    prod-url: TBC