name: Docker Build & Deploy

on:
  push:
    branches: [ "ci-cd-pipelines" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Build Docker Image
        run: |
          docker build -t steveh2707/treble-java-api:latest .
      - name: Publish Docker Image
        run: |
          docker login -u steveh2707 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push steveh2707/treble-java-api:latest