name: Docker Build & Deploy

on:
  push:
    branches: [ "ci-cd-pipelines" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          MYSQL_HOST: "localhost"
          MYSQL_PORT: "3306"
          MYSQL_DATABASE: "treble_db"
          MYSQL_USER: "root"
          MYSQL_PASSWORD: "Password1"
        run: mvn -DMYSQL_HOST=${MYSQL_HOST} -DMYSQL_PORT=${MYSQL_PORT} -MYSQL_DATABASE=${MYSQL_DATABASE} -DMYSQL_USER=${MYSQL_USER} -DMYSQL_PASSWORD=${MYSQL_PASSWORD} clean install
      - name: Build & Push the Docker image
        run: |
          docker build --build-arg